# Practical 8: File Input/Output Operations for Experimental Data Logging

### Computer Programming Lab – Chemical Engineering
**Syllabus Experiment:** **File input output operations for experimental data logging (CSV, JSON)**  
**Main Python Library:** `pandas`  
**Environment:** Google Colab / GitHub Codespaces + Jupyter Notebook + GitHub Copilot

---

## Important: Exact Syllabus Context

The complete experiment line in the syllabus is:

> **File input output operations for experimental data logging (CSV, JSON)**

For this practical, we will use **Pandas as the main tool** for reading, exploring, processing and writing experimental data. Students will work with both **CSV and JSON** files.

## How we will use AI Copilot

GitHub Copilot is your AI coding assistant. Use it to understand Pandas commands, interpret errors, ask for explanations and improve your data-processing logic.

**Do not ask Copilot to write the complete practical at the beginning.** First understand the structure of the experimental data and try the Pandas operation yourself. Then use Copilot for hints and debugging.

## 1. Learning Objectives

After completing this practical, you should be able to:

1. Understand why experimental data is stored in files.
2. Read CSV files using Pandas.
3. Read JSON files using Pandas.
4. Inspect rows, columns, data types and basic statistics.
5. Select and filter experimental records.
6. Handle simple missing or invalid values.
7. Create a new calculated column from experimental measurements.
8. Save processed data back to CSV and JSON.
9. Use GitHub Copilot to understand and debug Pandas operations.
10. Build a small experimental-data logging workflow relevant to chemical engineering.

## 2. Chemical Engineering Context – Experimental Data Logging

During a laboratory experiment, measurements may be recorded for variables such as:

- temperature
- pressure
- concentration
- reaction time
- flow rate
- pH
- yield

Instead of manually entering every value into a Python program, experimental measurements can be stored in files such as **CSV** and **JSON**.

In this practical, we will use a small teaching dataset representing measurements from a simplified chemical-process experiment.

Example structure:

| Experiment_ID | Time_min | Temperature_C | Pressure_bar | Concentration_mol_L |
|---|---:|---:|---:|---:|
| EXP001 | 0 | 25 | 1.00 | 1.00 |
| EXP001 | 10 | 30 | 1.05 | 0.92 |
| EXP001 | 20 | 35 | 1.10 | 0.84 |

**Important:** These are educational values for programming practice, not experimental design or validated process data.

## 3. Activity 1 – Create and Inspect Experimental Data

To make the notebook self-contained, create a small DataFrame first.

The columns will be:

- `Experiment_ID`
- `Time_min`
- `Temperature_C`
- `Pressure_bar`
- `Concentration_mol_L`

After creating the DataFrame, display it and inspect its structure.

In [ ]:
# pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [5]:

data = {
    'Experiment_ID': ['EXP001', 'EXP001', 'EXP001', 'EXP001', 'EXP002', 'EXP002', 'EXP002'],
    'Time_min': [0, 10, 20, 30, 0, 10, 20],
    'Temperature_C': [25, 30, 35, 40, 25, 32, 39],
    'Pressure_bar': [1.00, 1.05, 1.10, 1.15, 1.00, 1.08, 1.14],
    'Concentration_mol_L': [1.00, 0.92, 0.84, 0.76, 1.20, 1.05, 0.91],
    
    'pH': [4.2,5.8,6.5,7.0,8.3,9.1,9.8]
}

df = pd.DataFrame(data)
df

,Experiment_ID,Time_min,Temperature_C,Pressure_bar,Concentration_mol_L,pH
0,EXP001,0,25,1.00,1.00,4.2
1,EXP001,10,30,1.05,0.92,5.8
2,EXP001,20,35,1.10,0.84,6.5
3,EXP001,30,40,1.15,0.76,7.0
4,EXP002,0,25,1.00,1.20,8.3
5,EXP002,10,32,1.08,1.05,9.1
6,EXP002,20,39,1.14,0.91,9.8

### Copilot Activity 1 – Understand the DataFrame

Ask Copilot:

> I am a second-year chemical engineering student learning Pandas. Explain what a Pandas DataFrame represents in an experimental-data logging application. Explain rows, columns and index using my chemical experiment dataset. Do not write a complete program.

## 4. Activity 2 – Write the Experimental Data to CSV

Now save the DataFrame as a CSV file.

Use Pandas `to_csv()`.

Then verify that the file has been created.

### Think before coding

Why is CSV useful for exchanging experimental data between Python, Excel and other software?

In [6]:
# Activity 2
# Save df as a CSV file named chemical_experiment.csv
df.to_csv("chemical_experiment.csv",index=False)

### Copilot Activity 2 – `to_csv()`

Ask Copilot:

> Explain the important parameters of Pandas DataFrame.to_csv() for saving experimental data. In particular, explain why index=False is commonly used when exporting a DataFrame to a clean CSV file. Do not write the complete cell.

## 5. Activity 3 – Read the CSV File using Pandas

Now pretend that the experiment data has been received from a laboratory or another system.

Read the CSV file back into a new DataFrame using:

```python
pd.read_csv()
```

Display the data and verify that it matches the original dataset.

In [7]:
# Activity 3
# Read chemical_experiment.csv into a new DataFrame.
df_new = pd.read_csv('chemical_experiment.csv')
df_new

,Experiment_ID,Time_min,Temperature_C,Pressure_bar,Concentration_mol_L,pH
0,EXP001,0,25,1.00,1.00,4.2
1,EXP001,10,30,1.05,0.92,5.8
2,EXP001,20,35,1.10,0.84,6.5
3,EXP001,30,40,1.15,0.76,7.0
4,EXP002,0,25,1.00,1.20,8.3
5,EXP002,10,32,1.08,1.05,9.1
6,EXP002,20,39,1.14,0.91,9.8

## 6. Activity 4 – Inspect Experimental Data

Use Pandas to answer the following:

1. How many rows are present?
2. What are the column names?
3. What are the data types?
4. What are the first 3 records?
5. What are the last 2 records?
6. What are the basic statistics of the numerical columns?

Useful Pandas methods to investigate:

```text
shape
columns
dtypes
head()
tail()
describe()
info()
```

### Copilot Activity 3 – Data Inspection

Ask Copilot:

> I have a Pandas DataFrame containing chemical experimental measurements. Explain when I should use shape, columns, dtypes, head(), tail(), info() and describe(). Do not write a complete program.

In [13]:
# Activity 4
# Inspect the structure and summary of the experimental dataset.
print("\nDataFrame Info:")
df_new.info()
print('-----------------------------------------------------------------------------------------------------------------')
print("\nSummary Statistics:")
print(df_new.describe())
print('-----------------------------------------------------------------------------------------------------------------')
print("\nTail of the DataFrame:")
print(df_new.tail())
print('-----------------------------------------------------------------------------------------------------------------')
print("\nHead of the DataFrame:")
print(df_new.head()) 
print('-----------------------------------------------------------------------------------------------------------------')
print("\nColumn Names:")
print(df_new.columns)
print('-----------------------------------------------------------------------------------------------------------------')
print("\nData Types:")
print(df_new.dtypes)

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Experiment_ID        7 non-null      str
 1   Time_min             7 non-null      int64
 2   Temperature_C        7 non-null      int64
 3   Pressure_bar         7 non-null      float64
 4   Concentration_mol_L  7 non-null      float64
 5   pH                   7 non-null      float64
dtypes: float64(3), int64(2), str(1)
memory usage: 468.0 bytes
-----------------------------------------------------------------------------------------------------------------

Summary Statistics:
        Time_min  Temperature_C  Pressure_bar  Concentration_mol_L        pH
count   7.000000       7.000000      7.000000             7.000000  7.000000
mean   12.857143      32.285714      1.074286             0.954286  7.242857
std    11.126973       6.102302      0.061062             0.144667  1.960321
min     0.000000      25.000000      1.000000             0.760000  4.200000
25%     5.000000      27.500000      1.025000             0.875000  6.150000
50%    10.000000      32.000000      1.080000             0.920000  7.000000
75%    20.000000      37.000000      1.120000             1.025000  8.700000
max    30.000000      40.000000      1.150000             1.200000  9.800000
-----------------------------------------------------------------------------------------------------------------

Tail of the DataFrame:
  Experiment_ID  Time_min  Temperature_C  Pressure_bar  Concentration_mol_L  \
2        EXP001        20             35          1.10                 0.84
3        EXP001        30             40          1.15                 0.76
4        EXP002         0             25          1.00                 1.20
5        EXP002        10             32          1.08                 1.05
6        EXP002        20             39          1.14                 0.91

    pH
2  6.5
3  7.0
4  8.3
5  9.1
6  9.8
-----------------------------------------------------------------------------------------------------------------

Head of the DataFrame:
  Experiment_ID  Time_min  Temperature_C  Pressure_bar  Concentration_mol_L  \
0        EXP001         0             25          1.00                 1.00
1        EXP001        10             30          1.05                 0.92
2        EXP001        20             35          1.10                 0.84
3        EXP001        30             40          1.15                 0.76
4        EXP002         0             25          1.00                 1.20

    pH
0  4.2
1  5.8
2  6.5
3  7.0
4  8.3
-----------------------------------------------------------------------------------------------------------------

Column Names:
Index(['Experiment_ID', 'Time_min', 'Temperature_C', 'Pressure_bar',
       'Concentration_mol_L', 'pH'],
      dtype='str')
-----------------------------------------------------------------------------------------------------------------

Data Types:
Experiment_ID              str
Time_min                 int64
Temperature_C            int64
Pressure_bar           float64
Concentration_mol_L    float64
pH                     float64
dtype: object

## 7. Activity 5 – Filter Experimental Records

Use Pandas filtering to answer questions such as:

### Question A
Show only observations where:

```text
Temperature_C > 30
```

### Question B
Show only records from `EXP001`.

### Question C
Show observations where temperature is above 30 °C **and** pressure is greater than 1.05 bar.

### Think

Why is filtering important when analyzing experimental data?

In [22]:
# Activity 5
# Write Pandas filtering expressions for Questions A, B and C.

#Question A: Filter the DataFrame to include only rows where the Temperature_C is greater than 30.
filtered_temp = df_new[df_new['Temperature_C'] > 30]
print("\nFiltered DataFrame (Temperature_C > 30):")
print(filtered_temp)
print('-----------------------------------------------------------------------------------------------------------------')
#question B: Filter the DataFrame to include only rows where the Pressure_bar is between 1.05 and 1.15 (inclusive).
filtered_pressure = df_new[(df_new['Pressure_bar'] >= 1.05) & (df_new['Pressure_bar'] <= 1.15)]
print("\nFiltered DataFrame (Pressure_bar between 1.05 and 1.15):")
print(filtered_pressure)
print('-----------------------------------------------------------------------------------------------------------------')
#question C: Filter the DataFrame to include only the rows where the concentration_mol_L is less than 1.0 and the pH is greater than 7.0.
filtered_concentration_ph = df_new[(df_new['Concentration_mol_L'] < 1.0) & (df_new['pH'] > 7.0)]
print("\nFiltered DataFrame (Concentration_mol_L < 1.0 and pH > 7.0):")
print(filtered_concentration_ph)

Filtered DataFrame (Temperature_C > 30):
  Experiment_ID  Time_min  Temperature_C  Pressure_bar  Concentration_mol_L  \
2        EXP001        20             35          1.10                 0.84
3        EXP001        30             40          1.15                 0.76
5        EXP002        10             32          1.08                 1.05
6        EXP002        20             39          1.14                 0.91

    pH
2  6.5
3  7.0
5  9.1
6  9.8
-----------------------------------------------------------------------------------------------------------------

Filtered DataFrame (Pressure_bar between 1.05 and 1.15):
  Experiment_ID  Time_min  Temperature_C  Pressure_bar  Concentration_mol_L  \
1        EXP001        10             30          1.05                 0.92
2        EXP001        20             35          1.10                 0.84
3        EXP001        30             40          1.15                 0.76
5        EXP002        10             32          1.08                 1.05
6        EXP002        20             39          1.14                 0.91

    pH
1  5.8
2  6.5
3  7.0
5  9.1
6  9.8
-----------------------------------------------------------------------------------------------------------------

Filtered DataFrame (Concentration_mol_L < 1.0 and pH > 7.0):
  Experiment_ID  Time_min  Temperature_C  Pressure_bar  Concentration_mol_L  \
6        EXP002        20             39          1.14                 0.91

    pH
6  9.8

### Copilot Activity 4 – Pandas Filtering

Ask Copilot:

> Explain how boolean filtering works in Pandas for an experimental DataFrame. Show conceptually how to combine two conditions using &. Do not write the complete solution for my dataset.

## 8. Activity 6 – Calculate a New Experimental Quantity

Create a new column called:

```text
Concentration_Change
```

For this teaching dataset, calculate the change from the initial concentration of each experiment.

For each experiment:

```text
Concentration_Change = Initial_Concentration - Current_Concentration
```

You will need to think about how to obtain the initial concentration for each `Experiment_ID`.

### Engineering interpretation

This demonstrates an important data-processing pattern: **raw experimental measurements can be transformed into derived quantities** before further analysis.

### Copilot Activity 5 – Derived Columns

Ask Copilot:

> I have experimental concentration measurements grouped by Experiment_ID. Explain how Pandas can be used to calculate the initial concentration for each experiment and then create a new column showing the change from the initial value. Explain the approach without writing the complete code.

In [24]:
# Activity 6
# Create Concentration_Change using Pandas.
df_new['Concentration_Change'] = df_new.groupby('Experiment_ID')['Concentration_mol_L'].diff().fillna(0)
print("\nDataFrame with Concentration_Change:")
df_new

DataFrame with Concentration_Change:

,Experiment_ID,Time_min,Temperature_C,Pressure_bar,Concentration_mol_L,pH,Concentration_Change
0,EXP001,0,25,1.00,1.00,4.2,0.00
1,EXP001,10,30,1.05,0.92,5.8,-0.08
2,EXP001,20,35,1.10,0.84,6.5,-0.08
3,EXP001,30,40,1.15,0.76,7.0,-0.08
4,EXP002,0,25,1.00,1.20,8.3,0.00
5,EXP002,10,32,1.08,1.05,9.1,-0.15
6,EXP002,20,39,1.14,0.91,9.8,-0.14

## 9. Activity 7 – Export Processed Data

After adding your calculated column, save the processed DataFrame as:

```text
chemical_experiment_processed.csv
```

Then read it again and verify that the new column is present.

In [28]:
# Activity 7
# Save the processed DataFrame and read it back.
df_new.to_csv('processed_data.csv', index=False)
df_read_back = pd.read_csv('processed_data.csv')    
print("\nDataFrame read back from processed_data.csv:")
df_read_back

DataFrame read back from processed_data.csv:

,Experiment_ID,Time_min,Temperature_C,Pressure_bar,Concentration_mol_L,pH,Concentration_Change
0,EXP001,0,25,1.00,1.00,4.2,0.00
1,EXP001,10,30,1.05,0.92,5.8,-0.08
2,EXP001,20,35,1.10,0.84,6.5,-0.08
3,EXP001,30,40,1.15,0.76,7.0,-0.08
4,EXP002,0,25,1.00,1.20,8.3,0.00
5,EXP002,10,32,1.08,1.05,9.1,-0.15
6,EXP002,20,39,1.14,0.91,9.8,-0.14

## 10. Activity 8 – JSON Experimental Data

CSV is convenient for tabular data, but JSON is also widely used for data exchange between applications.

Create a JSON version of the experimental dataset.

Use Pandas:

```text
DataFrame.to_json()
pd.read_json()
```

Try to preserve the tabular structure so that the JSON can be loaded back into a DataFrame.

### Copilot Activity 6 – CSV vs JSON

Ask Copilot:

> Explain the difference between CSV and JSON for storing experimental data. When might JSON be useful when a chemical laboratory system exchanges data with another software application? Keep the explanation suitable for a second-year chemical engineering student.

In [32]:
# Activity 8
# Save the experimental DataFrame as JSON and read it back using Pandas.
df_new.to_json('experimental_data.json', orient='records', lines=True)
df_json_read_back = pd.read_json('experimental_data.json', orient='records', lines=True)
print("\nDataFrame read back from experimental_data.json:")
df_json_read_back

DataFrame read back from experimental_data.json:

,Experiment_ID,Time_min,Temperature_C,Pressure_bar,Concentration_mol_L,pH,Concentration_Change
0,EXP001,0,25,1.00,1.00,4.2,0.00
1,EXP001,10,30,1.05,0.92,5.8,-0.08
2,EXP001,20,35,1.10,0.84,6.5,-0.08
3,EXP001,30,40,1.15,0.76,7.0,-0.08
4,EXP002,0,25,1.00,1.20,8.3,0.00
5,EXP002,10,32,1.08,1.05,9.1,-0.15
6,EXP002,20,39,1.14,0.91,9.8,-0.14

## 11. Activity 9 – Handle Missing Experimental Values

Real experimental datasets may contain missing measurements.

Create a copy of your dataset and intentionally introduce a missing value in `Pressure_bar`.

Then:

1. Detect missing values using `isna()` or `isnull()`.
2. Count missing values in each column.
3. Decide how you would handle the missing pressure value.

For this practical, you may demonstrate filling the missing value with the column mean, but remember:

**In a real laboratory study, the method used to handle missing measurements must be justified scientifically.**

### Copilot Activity 7 – Missing Data

Ask Copilot:

> Explain how Pandas detects missing values using isna(), and explain the difference between deleting a missing observation and filling it with a value such as the mean. Use experimental chemical data as the example. Do not write the complete solution.

In [34]:
# Activity 9
# Create a missing value, detect it and demonstrate an appropriate handling method.
df_new.loc[0, 'Concentration_mol_L'] = None  # Introduce a missing value
print("\nDataFrame with a missing value:")
print(df_new)

DataFrame with a missing value:
  Experiment_ID  Time_min  Temperature_C  Pressure_bar  Concentration_mol_L  \
0        EXP001         0             25          1.00                  NaN
1        EXP001        10             30          1.05                 0.92
2        EXP001        20             35          1.10                 0.84
3        EXP001        30             40          1.15                 0.76
4        EXP002         0             25          1.00                 1.20
5        EXP002        10             32          1.08                 1.05
6        EXP002        20             39          1.14                 0.91

    pH  Concentration_Change
0  4.2                  0.00
1  5.8                 -0.08
2  6.5                 -0.08
3  7.0                 -0.08
4  8.3                  0.00
5  9.1                 -0.15
6  9.8                 -0.14

In [35]:
print("\nDetecting missing values:")
missing_values = df_new.isnull().sum()
print(missing_values)

Detecting missing values:
Experiment_ID           0
Time_min                0
Temperature_C           0
Pressure_bar            0
Concentration_mol_L     1
pH                      0
Concentration_Change    0
dtype: int64

## 12. Activity 10 – Simple Experimental Data Summary

Use Pandas to calculate:

1. Average temperature for each experiment.
2. Maximum pressure for each experiment.
3. Final concentration for each experiment.

Use grouping by `Experiment_ID`.

### Engineering interpretation

This is a basic example of converting raw experimental logs into a compact summary that an engineer could inspect before further analysis.

In [38]:
# Activity 10
# Create an experiment-level summary using groupby().
df_summary = df_new.groupby('Experiment_ID').agg({
    'Temperature_C': ['mean', 'min', 'max'],
    'Pressure_bar': ['mean', 'min', 'max'],
    'Concentration_mol_L': ['mean', 'min', 'max'],
    'pH': ['mean', 'min', 'max'],
    'Concentration_Change': ['mean', 'min', 'max']  

}).reset_index()
print("\nExperiment-level summary:")
df_summary

Experiment-level summary:

  Experiment_ID Temperature_C         Pressure_bar             \
                         mean min max         mean  min   max
0        EXP001          32.5  25  40     1.075000  1.0  1.15
1        EXP002          32.0  25  39     1.073333  1.0  1.14

  Concentration_mol_L                    pH           Concentration_Change  \
                 mean   min   max      mean  min  max                 mean
0            0.840000  0.76  0.92  5.875000  4.2  7.0            -0.060000
1            1.053333  0.91  1.20  9.066667  8.3  9.8            -0.096667


    min  max
0 -0.08  0.0
1 -0.15  0.0

In [40]:
df_summary = df_new.groupby('Experiment_ID').agg({
    'Temperature_C': ['mean'],
    'Pressure_bar': [ 'max'],
    'Concentration_mol_L': [ 'max'],
    'pH': [ 'min'],
    'Concentration_Change': ["last"]  

}).reset_index()
print("\nExperiment-level summary:")
df_summary

Experiment-level summary:

,Experiment_ID,Temperature_C,Pressure_bar,Concentration_mol_L,pH,Concentration_Change
,,mean,max,max,min,last
0,EXP001,32.5,1.15,0.92,4.2,-0.08
1,EXP002,32.0,1.14,1.20,8.3,-0.14

## 13. Copilot Debugging Challenge

The following code contains a common Pandas mistake.

Study it **before** asking Copilot.

```python
df[df['Temperature_C'] > 30 and df['Pressure_bar'] > 1.05]
```

### Your task

1. Run the code.
2. Observe the error.
3. Identify why Python's `and` is not appropriate here.
4. Ask Copilot:

> My Pandas filtering expression uses 'and' between two Series conditions and gives an error. Explain why Pandas requires a different operator and why each condition needs parentheses. Do not rewrite my complete program.

5. Correct the expression yourself.

In [41]:
# Run the intentionally incorrect filtering expression here.
df[df['Temperature_C'] > 30 & df['Pressure_bar'] > 1.05]

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

### Explain the error in your own words

Write your explanation here before continuing.

## 14. Final Mini-Project – Chemical Experimental Data Logger

Build one clean Pandas-based program/notebook workflow for processing experimental data.

Your final workflow should:

1. Create or load experimental data from CSV.
2. Display the dataset.
3. Inspect its structure and data types.
4. Filter observations based on experimental conditions.
5. Calculate at least one derived experimental quantity.
6. Detect missing values.
7. Create an experiment-level summary using `groupby()`.
8. Save the processed dataset to CSV.
9. Save the processed dataset to JSON.
10. Read the saved JSON back into Pandas and verify it.

### Suggested output files

```text
chemical_experiment.csv
chemical_experiment_processed.csv
chemical_experiment.json
```

**Main requirement:** Use Pandas for the data-processing operations. Avoid manually processing rows with Python loops when a clear Pandas operation is available.

In [ ]:
# FINAL PROJECT
# Chemical Experimental Data Logger
# Build your complete Pandas-based workflow here.

## 15. Final Copilot Review

After completing the final project, ask Copilot:

> Review my Pandas workflow for chemical experimental data logging. Check my CSV and JSON input/output, DataFrame inspection, filtering, derived columns, missing-value handling, groupby summary and exported files. Do not rewrite my notebook; identify possible issues and explain them.

Make corrections only after you understand the feedback.

## 16. Reflection – What Did You Learn?

Answer in your own words:

1. What is a CSV file and why is it useful for experimental data?
2. What is JSON and how is it different from CSV?
3. Why is Pandas useful for chemical experimental data logging?
4. What does `read_csv()` do?
5. What does `to_csv()` do?
6. What does `read_json()` do?
7. Why is filtering useful in experimental data analysis?
8. What does `groupby()` help us do?
9. Why should missing experimental values be handled carefully?
10. What Pandas error did you debug in this practical?
11. What did Copilot help you understand or debug?
12. Can you explain your final workflow without opening Copilot?

## 17. Submission Checklist

- [ ] I created or loaded an experimental DataFrame.
- [ ] I wrote experimental data to CSV.
- [ ] I read CSV using Pandas.
- [ ] I inspected rows, columns and data types.
- [ ] I filtered experimental observations.
- [ ] I created a derived experimental quantity.
- [ ] I detected and handled a missing value.
- [ ] I created an experiment-level summary using `groupby()`.
- [ ] I wrote processed data to CSV.
- [ ] I wrote processed data to JSON.
- [ ] I read JSON back using Pandas.
- [ ] I completed the Copilot debugging challenge.
- [ ] I used Copilot for explanation and debugging rather than simply copying a complete solution.
- [ ] I can explain my final workflow.
- [ ] I saved the completed notebook in my GitHub repository.

## 18. Suggested Evaluation – Faculty Use

| Component | Marks |
|---|---:|
| CSV input/output using Pandas | 2 |
| JSON input/output using Pandas | 2 |
| DataFrame inspection and filtering | 1 |
| Derived quantity / data processing | 1 |
| Missing-value handling | 1 |
| Grouped experimental summary | 1 |
| Copilot usage and debugging | 1 |
| Student's ability to explain/modify the workflow | 1 |
| **Total** | **10** |

**Faculty note:** During evaluation, provide a small new CSV file and ask the student to load it, filter one condition, calculate one summary and save the result. Then ask why Pandas is preferable to manually processing every row for this type of tabular experimental data.